name: Publish on Release

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    name: Publish Package to npmjs.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Setup Registry
        shell: bash
        run: |
          echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} >> ~/.npmrc |
          echo @andrewronscki:registry=https://registry.npmjs.org/ >> ~/.npmrc

      - name: Install
        shell: bash
        run: npm install

      - name: Build
        shell: bash
        run: npm run build

      - name: Publish
        shell: bash
        run: npm publish --access public
